### ISSUE TITLE
Replace the holding voltage on the lifter with the brake.

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/robotdev#11]
We currently apply a holding voltage to hold the lifter in a given location.  This can vary based on battery level and possibly if we need to change the motor.  We need to switch this to something more immune to changes.  A PID controller would work, but even better is the brake that is mounted on the lifter.  We should change the code so that when software wants the lifter stationary we apply the brake.

**Comment by Kassaba** [comment]
We are currently waiting for mechanical to install the larger pneumatic cylinder so that the break will have enough strength to hold up the lift.

**Comment by macovskym** [comment]
This has been added along with the ability to switch between using holding voltages and using the brake via the params file.  However, it still needs to be tested.

**Comment by macovskym** [comment]
The locking has been tested, but the holding voltages needs to be re-tuned.
