### ISSUE TITLE
Autonomous step for moving the grabber to an angle

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/robotdev#13]
When thinking about a two cube auto, we need to collect a cube.  While driving to collect a cube it would be nice to hold the grabber open pretty wide to our destination so when we close we still collect the cube even if we are not dead on the cube.

**Comment by Kassaba** [comment]
Change milestone?

**Comment by sjcbulldog** [comment]
This has been replaced with a step to collect a cube.
