### ISSUE TITLE
Add timeout to lift operations in autonomous

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/robotdev#29]
If there is something wrong with the lift, this currently blocks autonomous operations beyond the lifter operations.  Specifically the robot does not drive forward and cross the line.  There should be a timeout that after it expires, the lift operations fail and complete and the robot just crosses the line.

**Comment by macovskym** [comment]
Code for this has now been added but needs testing.

**Comment by sjcbulldog** [comment]
We have fixed this in a different way.  We have any initial blocking operations with the lift be in the background ensuring we cross the line.
