### ISSUE TITLE
Create a new driver stations based on the new laptop

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/robotdev#33]
The driver stations were flakey at best at the Wilsonville event.  The new laptop needs to get setup as a driver stations and one of the existing driver stations needs to be wiped clean, windows 10 installed, and it should be made ready as a backup driver stations.

**Comment by macovskym** [comment]
Test comment

**Comment by macovskym** [comment]
Test comment 2

**Comment by macovskym** [comment]
Test comment 3

**Comment by Kassaba** [comment]
Ready to close?

**Comment by sjcbulldog** [comment]
When we are 100% on the new driver station, lets wipe the old one clean and get it working well as well.  We can close when they are both ready.  Lets talk more at the meeting tonight.

**Comment by sjcbulldog** [comment]
Going to close this for now.  We are not going to redo the secondary driver station before Worlds.  We need to revisit drive station configurations during the summer.
