### ISSUE TITLE
Add curve to end of drive straight

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/robotdev#37]
We use the NAVX to drive the robot straight while driving a distance.  However, I think if we gradually change our target angle as we drive, we could add simple curves to our drive straight.  The biggest advantage would be a slight turn to the scale at the end of the scale drive straight to eliminate the need for the rotate step.  I am not sure if this will work, but it is worth spending an hour to look at it sometime.

**Comment by Kassaba** [comment]
Ready to close?
