### ISSUE TITLE
Automode: Opposite scale in under 15 seconds

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/robotdev#6]

**Comment by 1425** [comment]
I'm not sure if this is the right place to make this comment, but have you considered an auto that goes for either the switch or the scale, whichever happens to be the right color?  I know I tried to bring this up to some people early in the season but I'm not sure whether that made it in.

This could be a logical extension to that - go for one of the close scale side or the close switch side, and if neither of them are the right color then go for the opposite side of the scale.

**Comment by sjcbulldog** [comment]
Is this logan?

 

I think it is a great idea.

 

I just sent out an email about capturing these ideas in the issues section in github.

 

Can you put it in there?

 

Thanks
butch

**Comment by sjcbulldog** [comment]
The first cut at this shows we are going to be pushing the time limit to hit this in 15 seconds.  I would not remove this from possibility but make it a last priority.

**Comment by Kassaba** [comment]
Do we need to change the milestone on this?
