### ISSUE TITLE
Automode: Switch from backside, opposite side in under 15 seconds

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/robotdev#8]

**Comment by Kassaba** [comment]
Change milestone?

**Comment by sjcbulldog** [comment]
Yes, I am not sure this makes sense at all.  I am not clear how to do this reliably given the small window we have.  If we move cubes while carrying one, it is a penality, so we cannot make a spot for the robot.  We cannot shoot the cube so our window is very small (if it exists at all) for scoring the switch from the back side.

**Comment by Kassaba** [comment]
I’m not very worried about the ejecting part. Worst case, we can raise the lift a little bit higher and eject, launching it into the switch. Getting into position in the  given time will be harder.

**Comment by sjcbulldog** [comment]
But this is the switch, so we cannot launch the cube.  We must get our collector over the plane of the switch without herding any of the other cubes out of our way.

**Comment by Kassaba** [comment]
Yes, but I thought our collector sticks out more than 13 inches (the length of the cube). If this is true, when we butt up against the cube, we should be breaking the plane of the switch

**Comment by sjcbulldog** [comment]
That would be worth exploring.

**Comment by sjcbulldog** [comment]
Not going to do this as it kept falling below the priority line for auto mode work.  Auto development work for the season is now done, so closing this item.
