### ISSUE TITLE
Automode: Left/Right Start, pick switch/scale based on the one on the same side in under 15 seconds

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/robotdev#9]
Start: Outside

Switch: Same Side
Scale: Same Side
Action: Score on the scale

Switch: Opposite Side
Scale: Same Side
Action: Score on the scale

Switch: Same Side
Scale: Opposite Side
Action: Score on the switch

Switch: Opposite Side
Scale: Opposite Side:
Action: Score on the opposite scale

**Comment by tomisom** [comment]
How do we coordinate this automated behavior with other teams that don't have sophisticated auto modes? If they always go for the switch, and we sometimes go for the same switch if its closer, doesn't that increase the likelihood of collisions?

**Comment by sjcbulldog** [comment]
No, the assumption is that any robot starting in the center position owns the space in front of the switch. If we start on the outside and are going to score the switch, we must score it from the end or back side.

**Comment by Kassaba** [comment]
Do we need to update this to something along the lines of "score on switch prioritizing scale, score on switch prioritizing switch (if both are same side), If neither, cross auto line"?

**Comment by sjcbulldog** [comment]
We basically have this with the exception that in the last action we drive straight instead of scoring on opposite scale.  Scoring on the opposite scale is difficult and likely gets in the way of the robot on the other side.
